insert into provider (name, address1, address2, state, country) values("Guinness Storehouse", "St James's Gate", "Ushers", "Dublin 8", "Ireland") ;
insert into provider (name, address1, address2, state, country) values("United Breweries", "C/60", "Focal Point, Ludhiana", "Punjab 141010", "India") ;

insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("1", 4.1, 4.0, "Guinness is an Irish dry stout that originated in the brewery of Arthur Guinness at St. James's Gate, Dublin. Guinness is one of the most successful beer brands worldwide. It is brewed in almost 60 countries and is available in over 120. Annual sales total 850 million litres. A feature of the product is the burnt flavour that is derived from roasted unmalted barley, although this is a relatively modern development, not becoming part of the grist until the mid", "Guinness", "Guinness Storehouse");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("2", 4.4, 4.0, "Guinness is an Irish dry stout that originated in the brewery of Arthur Guinness at St. James's Gate, Dublin. Guinness is one of the most successful beer brands worldwide. It is brewed in almost 60 countries and is available in over 120. Annual sales total 850 million litres. A feature of the product is the burnt flavour that is derived from roasted unmalted barley, although this is a relatively modern development, not becoming part of the grist until the mid", "Guinness Draught Bitter", "Guinness Storehouse");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("3", 4.7, 4.0, "The head - Smooth, creamy and blonde. The Guiness Strong, dark and deep.", "Guinness Draught Guinness", "Guinness Storehouse");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("4", 4.9, 4.0, "Guinness is an Irish dry stout that originated in the brewery of Arthur Guinness at St. James's Gate, Dublin. Guinness is one of the most successful beer brands worldwide. It is brewed in almost 60 countries and is available in over 120. Annual sales total 850 million litres. A feature of the product is the burnt flavour that is derived from roasted unmalted barley, although this is a relatively modern development, not becoming part of the grist until the mid", "Guinness Foreign Extra Stout", "Guinness Storehouse");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("5", 8.0, 7.0, "Kingfisher is an Indian beer brewed by United Breweries Group, Bangalore. The brand was launched in 1978. With a market share of over 36% in India, it is also available in 52 other countries. The Heineken Group holds 42.4% equity shares in United Breweries Ltd.", "Kingfisher Premium", "United Breweries");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("6", 7.0, 6.0, "Kingfisher is an Indian beer brewed by United Breweries Group, Bangalore. The brand was launched in 1978. With a market share of over 36% in India, it is also available in 52 other countries. The Heineken Group holds 42.4% equity shares in United Breweries Ltd.", "Kingfisher Strong", "United Breweries");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("7", 6.5, 3.0, "Kingfisher is an Indian beer brewed by United Breweries Group, Bangalore. The brand was launched in 1978. With a market share of over 36% in India, it is also available in 52 other countries. The Heineken Group holds 42.4% equity shares in United Breweries Ltd.", "Kingfisher Strong Fresh", "United Breweries");
insert into beer (id, alcohol_percentage, cost, description, name, provider_name)values("8", 7.9, 4.0, "Kingfisher is an Indian beer brewed by United Breweries Group, Bangalore. The brand was launched in 1978. With a market share of over 36% in India, it is also available in 52 other countries. The Heineken Group holds 42.4% equity shares in United Breweries Ltd.", "Kingfisher Draught", "United Breweries");